### ISSUE TITLE
wifi and bluetooth not work for my nubia z11 mini s

### ISSUE THREAD

**Issue by rtgiskard** [HighwayStar/android_device_nubia_msm8953-common#1]
I'm searching for roms that's simple and stable but with extensible abilities these day, only for my mobile phone able to play movies on ext4 formated usb drive, the last one I'm tried is this, and it finally works at least for directly mount and read the usb drive, but unluckily the wifi and bluetooth does not work, it just stop with no response.

I'm using the twrp recory from:
[https://forum.xda-developers.com/android/development/rom-lineageos-15-1-nubia-z11-mini-s-t3842997]

wipe data, system, all cache before install the zip, after done, wipe cache, reboot system
and same procedure for the lineage 14.1 you porvide in another thread in xda, but it even can not boot. for lineage 15.1, evrything I test works except the wifi and bluetooth, and after install open gapps 8.1, found that the google framework stop to work too

I hope this may do some help, I'm really looking forward to the rom as it's indeed what I want, Thank you very much!

**Comment by HighwayStar** [comment]
If you use gapps, install it right after rom, before first boot. Now you can try to wipe data and do first boot with gapps installed. If it still doesnt help, maybe you have broken Persist partition. In that case you have to do full recover to stock rom first using Nubia emergency tool.

**Comment by rtgiskard** [comment]
thank you! I have just flashed the official rom and found that the wifi and bluetooth is still unusable ?! So strange!
it should not be the problem of this rom

**Comment by HighwayStar** [comment]
This means you have problem with /persist partition or with hardware. Try to full restore with Nubia emergency tool.

**Comment by rtgiskard** [comment]
that's really the case, I have the persist partition wiped in the recovery too, and this might be account for the strange behavior of my rom test ... so sorry ...... but you have done a great works! Thank you very much for my mobile phone!

**Comment by rtgiskard** [comment]
my god, tried several official rom, find no persist.img in, recover with the latest image v3.09, the persist partition seems not to be recovered, but I really need to go for a sleep now ...
